### ISSUE TITLE
retrieval of more than 250 results via the EDS API

### ISSUE THREAD

**Issue by ikgithub17** [ebsco/edsapi-php-sample#2]
EDS API return an error when  user click on the page results No 14
"Requested Records Starting at #261 Max startrequest number is 251"

![eds-api-issue](https://user-images.githubusercontent.com/29541184/43772106-223203fe-9a52-11e8-8191-e1ac42c71115.png)

**Comment by cwolfebsco-zz** [comment]
Thank you for reporting this. The problem has to do with session management within the application, I will review this in detail and provide a fix.

**Comment by cwolfebsco-zz** [comment]
Hello,

The problem was caused by a new session being used for every call and the action syntax thus not being able to take effect. Changes have been implemented and I would like to encourage you to test the proposed fix. I will send instructions via a separate eMail.

Claus

**Comment by cwolfebsco-zz** [comment]
From an eMail from Issam:

Hi Claus
 
I tested the proposed fix and I found out jumping the pages functioning well  . Thanks a lot
 
Regards
 
Issam Kattan

I will issue a pull request and approve it

**Comment by cwolfebsco-zz** [comment]
Closed with the most recent pull request
